import './globals.css'
import { Inter } from 'next/font/google'
import { draftMode } from 'next/headers'
import ExitDraftModeLink from './ExitDraftModeLink'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dev Felipe Ramos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {draftMode().isEnabled && (
          <p className='bg-orange-200 py-4 px-[6vw]'>
            Draft mode is enabled! <ExitDraftModeLink className="underline" />
          </p>
        )}
        {children}
      </body>
    </html>
  )
}
